### ISSUE TITLE
Tried both of my PS2's, one worked, one didnt.

### ISSUE THREAD

**Issue by fireether** [CTurt/FreeDVDBoot#1]
I didn't see any where to start contributing reports on what works and what does not work.

SCPH-30001R, Browser: 1.20, CD Player: 1.20, PlayStation Driver: 1.10, DVD Player 2.10U
This is a FAT PS2, dvd exploit did not work. DVD player menu came up, and pressing play gave the error "Cannot read disc". 

The slim model worked. SCPH-70012, Browser: 1.40, CD Player: 2.00, Playstation Driver 1.11, DVD Player 3.10U

Not sure if this will be helpful, but if others can add in what models they tried and what versions, we could see what is exploitable. 

Maybe can keep a list in wiki?

**Comment by JayFoxRox** [comment]
> [...] what works and what does not work.

[The README clearly says](https://github.com/CTurt/FreeDVDBoot/blob/baf2f195ccd0f53ea6c34fd6b48b365723a0b877/README.md#step-1-identify-your-dvd-player-version):

> For initial release only DVD Player version 3.10E is supported (as that's the console I have) - UPDATE: someone tested 3.10E exploit on 3.10U and it worked, so I guess region doesn't matter. In the future I may look at other firmware versions, and hopefully over time other developers from the scene will also contribute support for additional DVD Player versions.

The filenames also strongly imply this.

> Maybe can keep a list in wiki?

The README is more suitable if explicit support for each version has to be added.

However, GitHub Projects and Wiki tabs should be disabled unless they are actually used. The wiki could be enabled, but I can't think of a good use-case for now.
Due to bugs in GitHub, the first wiki article must be created by the project owner, as the "Wiki" button is broken for all other users. So if it's planned to be used, a "Home" article should be added.

**Comment by misterhat** [comment]
I just tried 3.11U and it loaded as a DVD video, but the screen flashes and goes black after I load it.

**Comment by misterhat** [comment]
It worked! https://i.imgur.com/9f8oScZ.png

My model information: https://i.imgur.com/dgnXOCp.png (SPCH-79001)

**Comment by CTurt** [comment]
Good to hear more reports confirming it's working on supported firmwares. Closing this
