### ISSUE TITLE
Not working with dvd player version 3.11M

### ISSUE THREAD

**Issue by Alex25197** [CTurt/FreeDVDBoot#102]
Hello all, I can't boot FreeDVDBoot correctly, I tried with the hybrid 3.10 and 3.11 version(in a DVD-R) and the non hybrid 3.11 only version(burned in a DVD-RW), both with the same outcome, it says "Could not read disk". 
The hybrid iso, was burned with Imgburn at 1x speed and the second one with Imgburn too but at 2.4x speed.

Any suggestions?

**Comment by CTurt** [comment]
Can your console play normal DVD videos?

**Comment by Alex25197** [comment]
> 
> 
> Can your console play normal DVD videos?

Hey, sorry for late response, yeah, it can play DVD videos, just tested with an old Max Steel movie I had and it worked. Ps2 version is SCPH-900010 I think, red version.

**Comment by Protofall** [comment]
Its a bad idea to use DVD-RW since they're harder to read. You might also have a bad brand of DVD-R/W that just can't be read well. Also the slower the burn speed, the better

**Comment by Alex25197** [comment]
> 
> 
> Its a bad idea to use DVD-RW since they're harder to read. You might also have a bad brand of DVD-R/W that just can't be read well. Also the slower the burn speed, the better

Any recommendation? both DVDs were Maxell brand.

**Comment by Protofall** [comment]
I'm more familiar with CD brands than DVDs, so I'm not sure. For CDs Verbatim is good so maybe their DVDs are also of a good quality.

**Comment by renanbianchi** [comment]
i have a 3.11M and i can confirm that it does work.

**Comment by deba5er** [comment]
Not a great test, since my SCPH-90010 is modified - Matrix 1.93.  Using 3.10/3.11 hybrid downloaded 7/2/2020 burned using imgburn to Verbatim DVD-R.
Tested with nothing in memory card or USB slots, one PS2 controller (official) connected.
With unit off, inserted disc, closed lid.  Pressed power button while holding Start button.  Tapped power button after "Disabled" dialogue shown on screen.  Booted into wLE.
Same boot to wLE working without disabling by holding O while starting from power off and disc inserted.

**Comment by Alex25197** [comment]
Hey! Sorry for the really late response, I was busy with university.  Just to update this, I got it fixed, just tested with the iso again, burned at 1x with another burning software and it worked!(I have used imgburn before). So Im gonna close this, thanks everyone for your help.
