### ISSUE TITLE
Why doesn't this work on a DVD+RW?

### ISSUE THREAD

**Issue by Tert1947** [CTurt/FreeDVDBoot#12]
I was trying to do this exploit with a DVD+RW, but it continuously gave me an "Unable to read the disc." error after inserting the disc on a PS2 Slim, disc drive model 3.11U. Is there something with the hard-coding of the disc, or is it just a simple error that i missed? Will this ever be possible with a DVD+RW?

**Comment by Protofall** [comment]
This guy says he use a DVD+RW and it works. https://www.youtube.com/watch?v=M9b15v-4l6I

From experience you could have a bad brand of DVDs. For example on Dreamcast with CD-Rs, I have Phillips discs and unbranded ones. The unbranded ones almost never work and phillips almost always works.

Also if you can, set your DVD burn speed as low as possible since higher speed means less accuracy and potential errors.

Btw what's your console version?

**Comment by CTurt** [comment]
This isn't really related to the exploit, but just the console's ability to read those type of discs. DVD+RW may work, but it's not recommended because it's harder for the PS2 laser to read and will wear it out faster. I will try to update the readme to make this clearer.

**Comment by zacchi4k** [comment]
Older drives, or drives with worn out lens, may fail to read RW media becaus the pits and lands are less distinct compared to a stamped or an R equivalent. And as CTurt said, even if it works it puts more strain on the lens so it's not recommended
