### ISSUE TITLE
Running games

### ISSUE THREAD

**Issue by jjuukas** [CTurt/FreeDVDBoot#18]
Not sure if this is the right place to ask but I'm new to this and I'm not sure how to run a game? Managed to burn and boot on prebuilt iso and how do I start a game from usb now? As I understand it should be an ELF file although I have no idea what that is... Thanks

**Comment by darkblood159** [comment]
you should start off by trying to make a mcboot card with the fmcb installer homebrew and then getting opl and some other homebrew and software im not completely sure myself but thats what i think you have to do.

**Comment by stendarr** [comment]
@jjuukas The prebuilt ISOs contain uLaunchELF, a program which can launch [ELF Binaries](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format). If your USB stick is supported by the PS2, the easiest way to start a game is: 

1. Download the [Open PS2 Loader](https://github.com/ps2homebrew/Open-PS2-Loader/releases/download/0.9.3/OpenPS2Loader_0.9.3.zip) (OPL). It is free software, just like this project.
2. Place the extracted contents on your USB stick.
3. Create a folder called `DVD` in the root directory of your USB stick and put the game ISO into the `DVD` folder.
4. Start the PS2 with your newly burnt FreeDVDBoot DVD and your USB stick inserted.
5. Select `mass0:/` or `mass:/` in the file browser of uLaunchELF, navigate to `OpenPS2Loader_0.9.3` -> `OPL 0.9.3 (Childproof)` and open `OPL 0.9.3 (Childproof).ELF` with circle.

Now OPL should be running, in the settings you can set the `USB device start mode` to `Manual`. After that you can simply click circle to show a list of the games you have on your thumbdrive.

If uLaunchELF shows the contents of `mass:/` to be empty then either your thumbdrive is not formatted properly (FAT32) or it simply isn't supported by the PS2 - I've tried a lot of sticks and especially newer ones have a tendency to not work. 


Here are some additional videos that might help you further:
- https://www.youtube.com/watch?v=16LZNZ442ew
- https://www.youtube.com/watch?v=zAfrnKj85G0
- https://www.youtube.com/watch?v=KGV8J8pPWfs
- https://www.youtube.com/watch?v=E8QlEuVPNuM

Note that you do not need FreeMCBoot like @darkblood159 said in order to launch uLaunchELF or OPL, it is however very convenient to have a memory card with FMCB - it provides several tools including emulators and since it lives exclusively in the memory card it frees up your DVD drive for other stuff.

Instead of putting OPL on your stick you can also put it in inside the Filesystems folder before creating your own `exploit.iso` as described in step 3 of the Readme. I just thought the former would be easier for someone just starting out with this.

**Comment by darkblood159** [comment]
Sorry that's why I said I'm unsure.

**Comment by jjuukas** [comment]
I think I get it now, thank you both. I started looking for my memory card to install FMCB onto but it seems to have dissapeared into another dimension. @stendarr you came in at the right moment before I gave up :) I'm off to trying it by your guidance, my usb seemed to work with my console today, it displayed the files ok. I'll keep you posted

**Comment by ExactGosling721** [comment]
i did all the steps and when opl opens no games show up when i press circle, i believe it’s the game files i have  because in the youtube videos the files type they have says disc image file, but on my iso games the type reads “iso image” and i don’t no how to change it, any solution?

**Comment by stendarr** [comment]
> no games show up when i press circle

What does show up? Does the menu where the games *should* be show up or does the screen not change?

ISO images should be perfectly fine, what game are you trying to run? Have you tried it with other games? Does uLaunchELF show the ISO images inside the `DVD` folder?

**Comment by ExactGosling721** [comment]
rn the games i tried were mk shaolin monks and def jam vendetta, they show up as files under a dvd file on the ps2 itself where the dashboard is but when i go into opl nothing pops up but the settings menu

**Comment by ExactGosling721** [comment]
under my mass folder there’s 2 options, “dvd” folder and “opl loader folder“, if i open the dvd folder my 2 games are there and are next to white paper, i’m guessing to be marked, but they don’t do anything on the second folder is opl and when i open that i keep opening till i reach the child proof version ( like the one the guy above said to open), then opl opens and there’s only 3 choices, “about” “exit” and “power off” under “about“ it’s a list of etc and at the bottom you’re promoted to press “ok” and it’s takes you back to the beginning but at the bottom left it says “games list “ next to circle and i press it but nothing happens

**Comment by jjuukas** [comment]
@ExactGosling721 Hey! Method explained by @stendarr works for me except I open up OPL 0.9.3, not the childproof version. There are settings in there and then just follow his steps further. You can then open games list by pressing circle, and read them with X if I'm not mistaken, it says at the bottom of the screen. Much thanks to Dominik once again!
