### ISSUE TITLE
ps2 scph-77004 

### ISSUE THREAD

**Issue by marcociri** [CTurt/FreeDVDBoot#180]
Congratulations on the work done to find this method.
i performed all the burning steps but when i insert the DVD-R disc with the iso it tells me "please insert a playstation or playstation2 format disk". i tried to look at the previous problems, i don't have any mod-chip in the play, but even after i inserted a DVD movie (which worked normally) the same warning comes out.

**Comment by axcyia** [comment]
I'm having the same issue as you, but with a scph-79001. :/

**Comment by RinasSam** [comment]
Try these two things:
1-double pressing the start button with disc.
2-check laser. If it is dying this could happen.

**Comment by J013k** [comment]
If your PS2 has got problems with reading DVD-Videos and instead of "Disc read error" you are getting:
![https://thumbs.gfycat.com/CarelessWavyCorydorascatfish-size_restricted.gif](https://thumbs.gfycat.com/CarelessWavyCorydorascatfish-size_restricted.gif)

Open it and look for modchip or any other modification.
Additionally you take out all memory cards.
Theoretically it could be a laser problem,
but as I mentioned before you should get  "Disc read error" if there will be a problem with it.

Try to also check few others DVD-Video discs.

I tested "All PS2 Slims - English language.iso" on the same console (SCPH-77004) and everything was fine.
Also my PS2 plays all DVD-Videos without a problem.

**Comment by ghost** [comment]
@J013k for me ps2(9004) stuck on "reading disk" unlimted times after i saw black screen and go to saved menu and tried to remove and insert disc agian (freedvdboot) All PS2 Slims - English language.iso on DVD-R, even i tried DVD-Video discs but it just show only black screen and gone .

what is the problem and what is  solution?

**Comment by J013k** [comment]
First things first.
What type of a DVD writer do you have?
Internal\external, brand, model...
What brand of DVD-R discs did you use?

What do you mean by "...i tried DVD-Video discs but it just show only black screen and gone."

DVD-Video discs do not work on your console, giving you only a black screen?

If DVD-Video discs do not work on your console, **this exploit also will not work**...

Maybe your console already has got modchip?
Do you have a warranty sticker at the back:
![https://i.postimg.cc/1zKhdDfv/pnLzVco.png](https://i.postimg.cc/1zKhdDfv/pnLzVco.png)
or under the console:
![https://i.postimg.cc/hGcNVhpT/ZMf-GOB2-GQs-DFm5-Xa.png](https://i.postimg.cc/hGcNVhpT/ZMf-GOB2-GQs-DFm5-Xa.png)

**Comment by marcociri** [comment]
I tried to redo the whole process and with the 1x speed it works now, thanks again.
