### ISSUE TITLE
PS2 Slim SCPH-75001 DVD Type 3.11U "Insert PS2 format disk error"

### ISSUE THREAD

**Issue by blueking1122** [CTurt/FreeDVDBoot#183]
So first I downloaded and burned the All PS2 Slims - English language.iso file onto a DVD-R using UltraISO on 1x, but once I popped the DVD in on the browse page, it lead to the red "Insert a PS2 format disk" error page. Next, I took another DVD-R 
using CDBURNERXP with Verify disk, 1x speed, and DVD high compatibility enabled but it showed the same page. To confirm that the laser was working, I played Monty Python and The Holy Grail (great movie btw, go watch it) and a PS2 game (Grand Turisimo 4) and both were successful. Any ideas to what's happening?

**Comment by J013k** [comment]
What type of DVD writer do you have?
Internal\external, brand, model...
What brand of DVD-R discs did you use?

**Comment by blueking1122** [comment]
I used an internal Toshiba/Samsung DVD writer model SH-S203
I honestly don't know what brand the blank disks are, they were unlabeled

EDIT: I found a stack of blank Maxell DVDs, im going to test it right now

**Comment by J013k** [comment]
- Samsung SH-S203B:
http://www.cdrlabs.com/reviews/samsung-sh-s203b-20x-dvdrw/all-pages.html.
- Samsung SH-S203N:
http://www.cdrlabs.com/reviews/samsung-sh-s203n-20x-dvdrw/all-pages.html.

The lowest writing speed that this DVD-writer has got for DVD-R discs is:
- 2x (probably ~2.4x) CLV: [Constant Linear Velocity](https://en.wikipedia.org/wiki/Constant_linear_velocity)
- 8x, Z-CLV: [Zoned Constant Linear Velocity](https://en.wikipedia.org/wiki/Constant_linear_velocity#Zoned_Constant_Linear_Velocity) 
- 12x CAV: [Constant Angular Velocity](https://en.wikipedia.org/wiki/Constant_angular_velocity)

So there should not be a possibility to write DVD-R with 1x speed, because firmware of this device will not allows to do it.
I mean it will use a higher speed.
Which one... I don't know...

**Comment by jamesy0ung** [comment]
I was using a SH-222BB and that may be the cause of my blank screen issue

**Comment by blueking1122** [comment]
UPDATE: I finally got it to work using an external DVD Writer at 8x speed. Now when I select the FMCB ELF file, it just brings me back to the main PS2 browser.

**Comment by J013k** [comment]
Did you copy all the files from FMCB archive or only "FMCBInstaller.elf"?
Did you try another flash-drive?
Which\What version of FMCB you wanted to install?

**Comment by blueking1122** [comment]
I downloaded and unzipped this file:
![image](https://user-images.githubusercontent.com/74525651/99891735-0b002080-2c22-11eb-912c-539c7a633db0.png)
Also, I copied the whole folder and put it into the USB.

**Comment by blueking1122** [comment]
FINAL UPDATE: I managed to open the Free MCBoot installer and now I can successfully launch into Free MCBoot upon startup. 
Thanks to everyone who commented on this issue!
-blueking1122
