### ISSUE TITLE
Will there be support for 2.13A in the future?

### ISSUE THREAD

**Issue by AxiomaticVertex** [CTurt/FreeDVDBoot#9]
I have a fat console with 2.13A DVD Player firmware. Unfortunately FreeDVDBoot doesn't seem to work, it recognizes it as a DVD however but it won't go any further or boot into FreeMCBoot, it just shows a black screen with DVD controls, unless I'm doing something wrong. I've burnt the hybrid 3.10 - 3.11 image it to a DVD-R disc at 4x speed and verified it with ImgBurn.

Is it also possible to update the firmware to the versions that are supported?

Thanks!

**Comment by YourKalamity** [comment]
as said in README.MD

Currently only support:
- 3.10 (all regions EUMACDGJ - 
- 3.11 (all regions EUMACDGJ -

**Comment by Protofall** [comment]
I imagine they'll try and support this firmware eventually, but dunno when. Supporting all firmwares will take a lot of time.

**Comment by CTurt** [comment]
As stated before, I plan to add support for maybe a couple more of the most common requests. But I'm really relying on the community to help here, because otherwise this will take me a long time. Hoping the porting process will accelerate after a few more are done, and I write some notes explaining it.
